backend:
  name: git-gateway
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor

media_folder: static/assets
public_folder: assets

collections:
  - name: course
    label: Course
    folder: _content/courses
    create: true
    slug: "{{slug}}"
    fields:
      - { name: title, label: Name }
      - { name: date, label: Date, widget: date }
      - { name: image, label: image, widget: image }
      - { name: description, label: Description, widget: markdown }